version: '3'

services:
  pyserver:
    build: pyserver_build
    network_mode: host
    ports:
      - 1234:1234

  pyclient:
    build: pyclient_build
    network_mode: 'host'
    depends_on:
      - pyserver